backend/apps/message/urls.py
from django.urls import path

from . import views

app_name = 'message'
urlpatterns = [
    path('', views.IndexMessageView.as_view(), name='index-message'),
    path('message/excel', views.ExcelMessageView.as_view(), name='excel-message'),
]

backend/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('apps.message.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('api/__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend/apps/message/models.py
from django.db import models
from solo.models import SingletonModel


class Message(models.Model):

    message = models.TextField('Сообщение')
    result = models.IntegerField('Результат классификации', default=0)
    percent = models.IntegerField('Вероятность', default=0)


class MessageSettings(SingletonModel):

    finodays_excel = models.FileField(upload_to='documents')
    example_excel = models.FileField(upload_to='documents')

backend/apps/message/forms.py
from django import forms


class MessagreForm(forms.Form):

    message = forms.CharField(label='Текст сообщения', required=True)


class ExcelMessagreForm(forms.Form):

    excel_file = forms.FileField(label='Файл эксель') #, validators=[validate_file_extension])

backend/apps/message/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from .constants import MESSAGE_COLOR_TEXT
from .forms import MessagreForm, ExcelMessagreForm
from .models import Message, MessageSettings

from .services import MessageColorService


class IndexMessageView(TemplateView):
    template_name = 'message/index.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['message_settings'] = MessageSettings.get_solo()
        return ctx

    def post(self, request):

        form = MessagreForm(self.request.POST)
        category, percent = None, None
        if form.is_valid():
            data = form.cleaned_data
            message_text = data.get('message')
            service = MessageColorService()
            category, percent = service.get_message_color(msg=message_text)
            message = Message(message=message_text, result=category, percent=percent)
            message.save()

        ctx = self.get_context_data()
        category = MESSAGE_COLOR_TEXT.get(category)
        ctx.update({'category': category, 'percent': percent})
        return render(request, self.template_name, ctx)


class ExcelMessageView(IndexMessageView):

    def post(self, request):
        form = ExcelMessagreForm(self.request.POST, self.request.FILES)
        excel_result = None
        if form.is_valid():
            excel_file = self.request.FILES['excel_file']
            service = MessageColorService()
            excel_result = service.get_message_color_from_excel(file=excel_file)
        ctx = self.get_context_data()
        ctx.update({'excel_result': excel_result})
        return render(request, self.template_name, ctx)

backend/templates/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

        {#{% block styles %}#}
        {#  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">#}
        {#{% endblock %}#}
        <title>Messages Clissifier</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    </body>
    {#{% block scripts %}#}
    {#    <script src="{% static 'js/index.js' %}"></script>#}
    {#{% endblock %}#}
</html>

backend/templates/message/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="{% get_media_prefix %}base/logo.jpg" alt="" height="80px">
            <h2>Определение эмоционального окраса сообщений в чате</h2>
            <p class="lead">Прототип сервиса, который с помощью машинного обучения определяет эмоциональный окрас входящих сообщений и классифицирует их в одну из трех категорий: негативные, позитивные или нейтральные.</p>
        </div>

        <div class="row justify-content-start">
            <div class="col-6 offset-md-1">
                <h3>Введите текст сообщения</h3>
                <form action="{% url 'message:index-message' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="message" class="form-label"></label>
                        <textarea id="message" class="form-control" name="message" required rows="6"></textarea>
                    </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>

            <div class="col-3  offset-md-1">
                <h3 class="realty_title">Результат</h3>
                {% if category %}
                    <br>
                    <h5>{{ category }}</h5>
                    <h5>Вероятность {{ percent }}%</h5>
                {% else %}
                    Здесь будет результат
                {% endif %}
            </div>
        </div>
        <hr class="my-4 col-10 offset-md-1">
        <div class="row justify-content-start">
            <div class="col-6 offset-md-1">
                <h3>Загрузите файл Excel</h3>
                <form action="{% url 'message:excel-message' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="excel-file" class="form-label"></label>
                        <input class="form-control" type="file" id="excel-file" name="excel_file" accept=".xlsx">
                    </div>
                <button type="submit" class="btn btn-primary">Загрузить</button>
                </form>
            </div>
            <div class="col-3 offset-md-1">
                <h3>Примеры файлов</h3>
                {% if message_settings.finodays_excel %}
                    <a href="{{ message_settings.finodays_excel.url }}" download  class="btn btn-link float-right">Скачать пример FINODAYS.xlsx</a>
                {% endif %}
            </div>


        <div class="col-10  offset-md-1">
            <h3 class="realty_title">Результат</h3>
            {% if excel_result %}
                {% for page in excel_result %}
                    <h3>{{ page.title }}</h3><br>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Date</th>
                                <th scope="col">Sender</th>
                                <th scope="col">Message</th>
                                <th scope="col">Category</th>
                                <th scope="col">Percent</th>
                            </tr>
                        </thead>
                        {% for message in page.messages %}
                                <tbody>
                                    <tr {% if message.Sender == 'CLIENT' %} class="table-secondary" {% endif %}>
                                        <td>{{ message.Date|date:'Y-m-d H:i' }}</td>
                                        <td>{{ message.Sender }}</td>
                                        <td>{{ message.Message }}</td>
                                        <td>{{ message.Category }}</td>
                                        <td>{% if message.Percent %}{{ message.Percent }}%{% endif %}</td>
                                    </tr>
                                </tbody>
                        {% endfor %}
                    </table>
                {% endfor %}

            {% else %}
                Здесь будут результаты
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}